name: Deploy AWS EC2 Shema

on:
  push:
    branches:
      - main # Configurado para rodar sempre que código novo subir na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploying via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT || 22 }}
          script: |
            cd /var/www/app || exit
            git pull origin main
            docker-compose up -d --build
            echo "Deploy Concluido com Sucesso!"
